import Foundation
import AppKit

/// Translation. SwiftUI looks literals such as `Text("Quiz")` up by their English text in the app bundle's
/// `Localizable.strings` (one per language, generated by scripts/make-localizations.py). `tr` does the same for text built in
/// code, with `{name}` placeholders: `tr("{n} of {total}", ["n": 3, "total": 10])`. A missing translation shows the English.
func tr(_ key: String, _ params: [String: Any] = [:]) -> String {
    var s = Bundle.main.localizedString(forKey: key, value: nil, table: nil)
    if s.isEmpty { s = key }
    for (k, v) in params { s = s.replacingOccurrences(of: "{\(k)}", with: "\(v)") }
    return s
}
/// Like `tr`, for short or ambiguous text (units): looks up "context|text" first.
func trc(_ context: String, _ key: String) -> String {
    let k = "\(context)|\(key)"
    let s = Bundle.main.localizedString(forKey: k, value: nil, table: nil)
    return s == k ? tr(key) : s
}

/// The languages the app is translated into. The choice is stored as the standard `AppleLanguages` override, so it also
/// translates the system menus; it takes effect the next time the app starts.
enum AppLanguage: String, CaseIterable, Identifiable {
    case system, en, ru, uk, zhHans = "zh-Hans", es, fr
    var id: String { rawValue }
    var label: String {
        switch self {
        case .system: return tr("System")
        case .en: return "English"
        case .ru: return "Русский"
        case .uk: return "Українська"
        case .zhHans: return "简体中文"
        case .es: return "Español"
        case .fr: return "Français"
        }
    }
    /// What is stored now (read from the app's own defaults, so a system-wide setting does not count as a choice).
    static var chosen: AppLanguage {
        guard let first = (UserDefaults.standard.persistentDomain(forName: Bundle.main.bundleIdentifier ?? "")?["AppleLanguages"] as? [String])?.first else { return .system }
        return AppLanguage(rawValue: first) ?? .system
    }
    func save() {
        if self == .system { UserDefaults.standard.removeObject(forKey: "AppleLanguages") }
        else { UserDefaults.standard.set([rawValue], forKey: "AppleLanguages") }
        UserDefaults.standard.synchronize()
    }
    /// Starts a fresh copy of the app and quits this one.
    static func relaunch() {
        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/usr/bin/open")
        p.arguments = ["-n", Bundle.main.bundlePath]
        try? p.run()
        NSApp.terminate(nil)
    }
}

import SwiftUI
extension Text {
    /// `Text(someString)` normally shows the string as is. Here it goes through the translation table first (a string with no
    /// translation, like a number or an element symbol, is shown unchanged).
    init(_ s: String) { self.init(verbatim: tr(s)) }
}

@MainActor enum L10nSelfTest {
    static func run() {
        SelfTest.check(tr("{n} of {total}", ["n": 3, "total": 10]) == "3 of 10", "l10n: placeholders are filled in (and English is the fallback)")
        SelfTest.check(tr("A string nobody translated") == "A string nobody translated", "l10n: a missing translation shows the English text")
        let cases: [(String, String, String)] = [
            ("ru", "галогены, открытые до 1850", "halogens discovered before 1850"),
            ("uk", "рідкі за кімнатної температури", "liquid at room temperature"),
            ("zh", "1850年之前发现的卤素", "halogens discovered before 1850"),
            ("es", "el gas noble más pesado", "heaviest noble gas"),
            ("fr", "point de fusion supérieur à 3000 K", "melting point above 3000 K"),
        ]
        for (lang, q, en) in cases {
            let a = ElementQuery.run(QueryVocab.normalize(q, language: lang))?.matches.map(\.z), b = ElementQuery.run(en)?.matches.map(\.z)
            SelfTest.check(a != nil && a == b && !(b ?? []).isEmpty, "l10n: the question box understands \(lang): \(q)", "\(String(describing: a)) vs \(String(describing: b))")
        }
        SelfTest.check(QueryVocab.normalize("halogens", language: "en") == "halogens", "l10n: English questions are left alone")
    }
}
