#!/usr/bin/env python3
"""Builds packaging/localization/<lang>.lproj/Localizable.strings for the Mac app.

The text comes from the web app's dictionaries (web/src/i18n/locales/*.json: English sentence -> translation), plus
packaging/localization-src/*.py for strings only the Mac app has (tuples of English, ru, uk, zh, es, fr).
SwiftUI looks literals up by their English text, and tr() in L10n.swift uses the same table with {name} placeholders.
"""
import glob, json, os
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
LANGS = {'ru': 'ru', 'uk': 'uk', 'zh': 'zh-Hans', 'es': 'es', 'fr': 'fr'}
ORDER = ['ru', 'uk', 'zh', 'es', 'fr']

extra = {l: {} for l in ORDER}
for f in sorted(glob.glob(os.path.join(ROOT, 'packaging/localization-src/*.py'))):
    ns = {}
    exec(open(f, encoding='utf-8').read(), ns)
    for row in ns['B']:
        assert len(row) == 6, row[0]
        for l, v in zip(ORDER, row[1:]):
            extra[l][row[0]] = v

def esc(s): return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')

out = os.path.join(ROOT, 'packaging/localization')
os.makedirs(os.path.join(out, 'en.lproj'), exist_ok=True)
open(os.path.join(out, 'en.lproj/Localizable.strings'), 'w').write('/* English is the source language; the keys are the English text. */\n')
for code, folder in LANGS.items():
    d = json.load(open(os.path.join(ROOT, f'web/src/i18n/locales/{code}.json'), encoding='utf-8'))
    # the Mac app sometimes words a string like the web app minus a leading symbol ("⚠ Invalid input" / "Invalid input")
    import re
    for k in list(d):
        bare = re.sub(r'^[^\w(]+', '', k)
        if bare and bare != k and bare not in d: d[bare] = re.sub(r'^[^\w(]+', '', d[k]) or d[k]
    d.update(extra[code])
    os.makedirs(os.path.join(out, f'{folder}.lproj'), exist_ok=True)
    with open(os.path.join(out, f'{folder}.lproj/Localizable.strings'), 'w', encoding='utf-8') as f:
        f.write('/* Generated by scripts/make-localizations.py. Do not edit. */\n')
        for k in sorted(d):
            if '|' in k and k.split('|')[0] in ('unit',): pass
            f.write(f'"{esc(k)}" = "{esc(d[k])}";\n')
    print(code, len(d))
